PROJECT_NAME: 'PAR for zs'

DATASET:
  TYPE: 'pedes'
  NAME: 'RAP2'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: True
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 192

FILES:
  BASE_DIR: &base_dir ./data
  GENERATED_DIR: !join [*base_dir, /generated]
  DISCARDED_DIR: !join [*base_dir, /discarded]
  CHECKING_DIR: !join [*base_dir, /checking]
  LABELING_DIR: !join [*base_dir, /labeling]
  DISCARDED_TRACKER: !join [*base_dir, /discarded, /reasons_tracker.txt]
  

GENERATION:
  IP_COMFY: ''
  MODEL_SD3:
    BASE_DIR: ''

CHECKER:
  BASE_DIR: ''
  FUNCTION_BYW:
    FILENAME: ''

ANNOTATION:
  BASE_DIR: './data/labeling'
  PAR_MODEL:
    PATH: './models/img_par_model/ckpt_max_2024-03-02_18:01:07.pth'
    BACKBONE_TYPE: 'resnet50'
    CLASSIFIER:
      NAME: 'linear'
      BN: False
      POOLING: 'avg'
      SCALE: 1
    DATASET:
      HEIGHT: 256
      WIDTH: 192