ANNOTATION:
  BASE_DIR: ./data/labeling
  CURRENT_SELECTED: 0
  MODELS:
  - BACKBONE_TYPE: resnet50
    CLASSIFIER:
      BN: false
      NAME: linear
      POOLING: avg
      SCALE: 1
    DATASET:
      HEIGHT: 256
      WIDTH: 192
    Name: pr_50_percent
    PATH: ./models/img_par_model/ckpt_max_2024-04-10_23:26:07.pth
    TYPE: PAR_MODEL
  - BACKBONE_TYPE: resnet50
    CLASSIFIER:
      BN: false
      NAME: linear
      POOLING: avg
      SCALE: 1
    DATASET:
      HEIGHT: 256
      WIDTH: 192
    Name: pr_90_percent
    PATH: ./models/img_par_model/ckpt_max_2024-04-10_23:26:07.pth
    TYPE: PAR_MODEL
AUTO_LABEL:
  CHECKBOX_THRESHOLD: 0.5
  CONFIDENCE_THRESHOLDS:
  - color: '#b6d7a8'
    value: 0.75
  - color: '#ffe599'
    value: 0.5
  DEFAULT_COLOR: '#ea9999'
DATASET:
  HEIGHT: 256
  LABEL: eval
  NAME: RA1234
  PATH: data/custom_dataset/dataset_zs_custom.pkl
  TRAIN_SPLIT: trainval
  TYPE: pedes
  VAL_SPLIT: test
  WIDTH: 192
  ZERO_SHOT: true
FILES:
  BASE_DIR: ./data
  CHECKING_DIR: ./data/checking
  DISCARDED_DIR: ./data/discarded
  DISCARDED_TRACKER: ./data/discarded/reasons_tracker.txt
  GENERATED_DIR: ./data/generated
  LABELING_DIR: ./data/labeling
GENERATION:
  BASE_OUTPUT_PATH: ./ComfyUI/output
  IP_COMFY: http://127.0.0.1:8188
  MODELS:
  - name: sd3_medium_incl_clips.safetensors
    path: /autofs/unitytravail/travail/sasifchaudhr/ComfyUI/models/checkpoints/sd3_medium_incl_clips.safetensors
  PROMPTS:
    negative: "Partial figures, cropped bodies, low-resolution images, blurred backgrounds,\
      \ no low-angle shots, no side views, avoid obscured faces. \n"
    positive: 'A highly detailed, ultra high definition image of a single pedestrian
      on an airport, with the pedestrian fully visible and centered in the frame. '
  filename: generated_image
  manual_quality_check: true
  model: sd3_medium_incl_clips.safetensors
  num_images: 3
  resolution_height: 1024
  resolution_width: 1024
  seed: null
  steps: 1
PROJECT_NAME: PAR for zs
QUALITY_CHECKS:
  BASE_DIR: ./backend/quality_checker
  FUNCTIONS:
  - args: []
    name: B&W
    path: backend/quality_checker/check_black_white.py
  - args: []
    name: Always true
    path: backend/quality_checker/check_always_true.py
  - args:
    - 10
    - 20
    name: Always false
    path: backend/quality_checker/check_always_false.py
  - args: 50
    name: Random
    path: ./backend/quality_checker/check_random.py
  selected_checks:
  - 0
  - 0
  - 0
  - 0
  - 0
