ANNOTATION:
  BASE_DIR: '!join [ *base_dir, /labeling ]'
  CURRENT_SELECTED: 0
  MODELS: []
AUTO_LABEL:
  CHECKBOX_THRESHOLD: 0.5
  CONFIDENCE_THRESHOLDS: []
  DEFAULT_COLOR: blue
  MAX_AUTO_LABEL: 11
DATASET:
  NAME: null
  PATH: data/custom_dataset/dataset_zs_custom.pkl
FILES:
  BASE_DIR: '&base_dir projects/test/config.yaml'
  CHECKING_DIR: '!join [ *base_dir, /checking ]'
  DISCARDED_DIR: '!join [ *base_dir, /discarded ]'
  DISCARDED_TRACKER: '!join [ *base_dir, /discarded/reasons_tracker.txt ]'
  GENERATED_DIR: '!join [ *base_dir, /generated ]'
  LABELING_DIR: '!join [ *base_dir, /labeling ]'
GENERATION:
  BASE_OUTPUT_PATH: ./ComfyUI/output
  IP_COMFY: http://127.0.0.1:8188
  MODELS: []
  PROMPTS:
    negative: ''
    positive: ''
  filename: generated_image
  manual_quality_check: true
  model: ''
  num_images: 3
  resolution_height: 1024
  resolution_width: 1024
  seed: null
  steps: 1
PROJECT_NAME: MyProject
QUALITY_CHECKS:
  BASE_DIR: ./backend/quality_checker
  FUNCTIONS: []
  selected_checks: []
